### PR TITLE
Filterfunction

### PR DESCRIPTION
**Pull request by danielab93**
Hi there,
I built a filter-function to filter for categories on every page and also on the favourites-page. Please check the filters on every page and also my code. Thanks :) 

#5

### CODE REVIEW

**Comment by kristina-voit** [comment]
Looks, all in all, good to me!
1) Please check - as just discussed via Zoom - the rendering issue of all categories when a filter option has been applied
2) The wrap function of the favorite-icon next to the title should be added manually to avoid browser-default-issues in displaying.

Keep up the good work! :-)

**Comment by danielab93** [comment]
Hey Kristina,
thanks a lot for checking my pull request! I edited the filterfunction and it should work now properly :) 
Please check again :)

**Comment by kristina-voit** [comment]
L pretty GTM! Ready for merge! 🥳

**Comment by danielab93** [comment]
THANK YOU!! :-)

**Pull request merged**
